### ISSUE TITLE
我可以继续使用 easy-release 的 NPM 库名吗？

### ISSUE THREAD

**Issue by cnlon** [fengcen/easy-release#1]
很遗憾看到 easy-release 已经弃用了。
之前我写了一个用于快速发布 NPM 库的小工具 [smart-release](https://github.com/cnlon/smart-release)，准备改名为 easy-release，发现 NPM 上 easy-release 已被您使用。看到 easy-release 您已经弃用，我希望可以继续发挥它的价值，真心希望您可以将 NPM 上 easy-release 库名赠送于我，不胜感激！
（如果您愿意，可以执行 `npm owner add cnlon easy-release`，我会在新的项目上注明：Thanks @fengcen for easy-release(NPM package name)，再次感激！）

**Comment by fengcen** [comment]
可以，我明天有空操作一下，这点小事不用谢，也不需要注明，谢谢。
lon <notifications@github.com>于2018年2月9日 周五00:28写道：

**Comment by fengcen** [comment]
操作了

**Comment by cnlon** [comment]
感谢！
